//
//  IconBodySys.h
//  ProjectName
//
//  Created by CAjemian on 1/15/16.
//  Copyright (c) 2016 HOBAJEM. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>


@interface IconBodySys : NSObject

// Drawing Methods
+ (void)drawIconsyscardiovasculorWithFrame: (CGRect)frame;
+ (void)drawIconsysgastroIntestinalWithFrame: (CGRect)frame;
+ (void)drawIconsysurologicalWithFrame: (CGRect)frame;
+ (void)drawIconsysmusculoSkeletonWithFrame: (CGRect)frame;
+ (void)drawIconsyspulmonaryWithFrame: (CGRect)frame;
+ (void)drawIconsysimmuneWithFrame: (CGRect)frame;
+ (void)drawIconsyscirculatoryWithFrame: (CGRect)frame;
+ (void)drawIconsysendocrineWithFrame: (CGRect)frame;
+ (void)drawIconsyscentralNervousWithFrame: (CGRect)frame;

// Generated Images
+ (UIImage*)imageOfIconsyscardiovasculorWithFrame: (CGRect)frame;
+ (UIImage*)imageOfIconsysgastroIntestinalWithFrame: (CGRect)frame;
+ (UIImage*)imageOfIconsysurologicalWithFrame: (CGRect)frame;
+ (UIImage*)imageOfIconsysmusculoSkeletonWithFrame: (CGRect)frame;
+ (UIImage*)imageOfIconsyspulmonaryWithFrame: (CGRect)frame;
+ (UIImage*)imageOfIconsysimmuneWithFrame: (CGRect)frame;
+ (UIImage*)imageOfIconsyscirculatoryWithFrame: (CGRect)frame;
+ (UIImage*)imageOfIconsysendocrineWithFrame: (CGRect)frame;
+ (UIImage*)imageOfIconsyscentralNervousWithFrame: (CGRect)frame;

@end
